CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS profiles (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
	full_name TEXT,
	date_of_birth DATE,
	phone TEXT,
	address TEXT,
	occupation TEXT,
	about_me TEXT,
	custom_instructions TEXT,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS custom_instructions TEXT;

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS telegram_chat_id BIGINT;

ALTER TABLE profiles
ADD COLUMN IF NOT EXISTS telegram_username TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_telegram_chat_id_unique
	ON profiles (telegram_chat_id)
	WHERE telegram_chat_id IS NOT NULL;

UPDATE profiles
SET custom_instructions = LEFT(custom_instructions, 2000)
WHERE custom_instructions IS NOT NULL
	AND LENGTH(custom_instructions) > 2000;

ALTER TABLE profiles
DROP CONSTRAINT IF EXISTS profiles_custom_instructions_length_check;

ALTER TABLE profiles
ADD CONSTRAINT profiles_custom_instructions_length_check
	CHECK (custom_instructions IS NULL OR LENGTH(custom_instructions) <= 2000);

CREATE TABLE IF NOT EXISTS chat_threads (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	title TEXT NOT NULL DEFAULT 'New chat',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_threads_user_last_message
	ON chat_threads (user_id, last_message_at DESC);

CREATE TABLE IF NOT EXISTS chat_messages (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
	content TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_created_at
	ON chat_messages (user_id, created_at DESC);

ALTER TABLE chat_messages
ADD COLUMN IF NOT EXISTS thread_id UUID;

DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1
		FROM pg_constraint
		WHERE conname = 'chat_messages_thread_id_fkey'
	) THEN
		ALTER TABLE chat_messages
		ADD CONSTRAINT chat_messages_thread_id_fkey
			FOREIGN KEY (thread_id)
			REFERENCES chat_threads(id)
			ON DELETE CASCADE;
	END IF;
END $$;

WITH users_with_legacy AS (
	SELECT DISTINCT user_id
	FROM chat_messages
	WHERE thread_id IS NULL
),
created_threads AS (
	INSERT INTO chat_threads (user_id, title, created_at, last_message_at)
	SELECT
		u.user_id,
		'Imported chat',
		COALESCE((
			SELECT MIN(m.created_at)
			FROM chat_messages m
			WHERE m.user_id = u.user_id AND m.thread_id IS NULL
		), NOW()),
		COALESCE((
			SELECT MAX(m.created_at)
			FROM chat_messages m
			WHERE m.user_id = u.user_id AND m.thread_id IS NULL
		), NOW())
	FROM users_with_legacy u
	RETURNING id, user_id
)
UPDATE chat_messages m
SET thread_id = t.id
FROM created_threads t
WHERE m.user_id = t.user_id
	AND m.thread_id IS NULL;

UPDATE chat_threads t
SET last_message_at = latest.last_message_at
FROM (
	SELECT thread_id, MAX(created_at) AS last_message_at
	FROM chat_messages
	WHERE thread_id IS NOT NULL
	GROUP BY thread_id
) latest
WHERE t.id = latest.thread_id;

DO $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM chat_messages WHERE thread_id IS NULL) THEN
		ALTER TABLE chat_messages ALTER COLUMN thread_id SET NOT NULL;
	END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_chat_messages_thread_created_at
	ON chat_messages (thread_id, created_at DESC);

CREATE TABLE IF NOT EXISTS documents (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	type TEXT NOT NULL CHECK (type IN ('aadhaar', 'passport', 'license', 'certificate', 'photo', 'other')),
	custom_type TEXT,
	file_url TEXT NOT NULL,
	storage_bucket TEXT NOT NULL DEFAULT 'keeba-files',
	storage_path TEXT NOT NULL,
	extracted_text TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE documents
ADD COLUMN IF NOT EXISTS custom_type TEXT;

UPDATE documents
SET custom_type = 'other'
WHERE type = 'other'
	AND (custom_type IS NULL OR LENGTH(BTRIM(custom_type)) = 0);

UPDATE documents
SET custom_type = LEFT(BTRIM(custom_type), 60)
WHERE type = 'other'
	AND custom_type IS NOT NULL;

UPDATE documents
SET custom_type = NULL
WHERE type <> 'other';

ALTER TABLE documents
DROP CONSTRAINT IF EXISTS documents_custom_type_rules_check;

ALTER TABLE documents
ADD CONSTRAINT documents_custom_type_rules_check
	CHECK (
		(
			type = 'other'
			AND custom_type IS NOT NULL
			AND LENGTH(BTRIM(custom_type)) > 0
			AND LENGTH(BTRIM(custom_type)) <= 60
		)
		OR (type <> 'other' AND custom_type IS NULL)
	);

CREATE INDEX IF NOT EXISTS idx_documents_user_created_at
	ON documents (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS telegram_link_codes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	code TEXT NOT NULL UNIQUE,
	expires_at TIMESTAMPTZ NOT NULL,
	consumed_at TIMESTAMPTZ,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_telegram_link_codes_user_active
	ON telegram_link_codes (user_id)
	WHERE consumed_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_telegram_link_codes_expires_at
	ON telegram_link_codes (expires_at);

CREATE TABLE IF NOT EXISTS telegram_inbound_messages (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	telegram_update_id BIGINT NOT NULL UNIQUE,
	telegram_message_id BIGINT,
	telegram_chat_id BIGINT NOT NULL,
	telegram_user_id BIGINT,
	user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
	message_text TEXT NOT NULL,
	received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_telegram_inbound_user_received_at
	ON telegram_inbound_messages (user_id, received_at DESC);

CREATE TABLE IF NOT EXISTS vault_items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	encrypted_payload TEXT NOT NULL CHECK (LENGTH(BTRIM(encrypted_payload)) > 0),
	iv TEXT NOT NULL CHECK (LENGTH(BTRIM(iv)) > 0),
	salt TEXT NOT NULL CHECK (LENGTH(BTRIM(salt)) > 0),
	kdf_algorithm TEXT NOT NULL DEFAULT 'pbkdf2-sha256',
	kdf_iterations INTEGER NOT NULL DEFAULT 600000 CHECK (kdf_iterations BETWEEN 200000 AND 2000000),
	key_version SMALLINT NOT NULL DEFAULT 1 CHECK (key_version >= 1),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vault_items_user_created_at
	ON vault_items (user_id, created_at DESC);

CREATE OR REPLACE FUNCTION update_profiles_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
	NEW.updated_at = NOW();
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON profiles;
DROP TRIGGER IF EXISTS trg_vault_items_updated_at ON vault_items;

CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION update_profiles_timestamp();

CREATE TRIGGER trg_vault_items_updated_at
BEFORE UPDATE ON vault_items
FOR EACH ROW
EXECUTE FUNCTION update_profiles_timestamp();

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE vault_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_link_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_inbound_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON profiles;
DROP POLICY IF EXISTS profiles_insert_own ON profiles;
DROP POLICY IF EXISTS profiles_update_own ON profiles;
DROP POLICY IF EXISTS profiles_delete_own ON profiles;

CREATE POLICY profiles_select_own
ON profiles FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY profiles_insert_own
ON profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY profiles_update_own
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY profiles_delete_own
ON profiles FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS chat_threads_select_own ON chat_threads;
DROP POLICY IF EXISTS chat_threads_insert_own ON chat_threads;
DROP POLICY IF EXISTS chat_threads_update_own ON chat_threads;
DROP POLICY IF EXISTS chat_threads_delete_own ON chat_threads;

CREATE POLICY chat_threads_select_own
ON chat_threads FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY chat_threads_insert_own
ON chat_threads FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_threads_update_own
ON chat_threads FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_threads_delete_own
ON chat_threads FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS chat_messages_select_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_insert_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_update_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_delete_own ON chat_messages;

CREATE POLICY chat_messages_select_own
ON chat_messages FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY chat_messages_insert_own
ON chat_messages FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_messages_update_own
ON chat_messages FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_messages_delete_own
ON chat_messages FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS documents_select_own ON documents;
DROP POLICY IF EXISTS documents_insert_own ON documents;
DROP POLICY IF EXISTS documents_update_own ON documents;
DROP POLICY IF EXISTS documents_delete_own ON documents;

DROP POLICY IF EXISTS vault_items_select_own ON vault_items;
DROP POLICY IF EXISTS vault_items_insert_own ON vault_items;
DROP POLICY IF EXISTS vault_items_update_own ON vault_items;
DROP POLICY IF EXISTS vault_items_delete_own ON vault_items;

DROP POLICY IF EXISTS telegram_link_codes_select_own ON telegram_link_codes;
DROP POLICY IF EXISTS telegram_link_codes_insert_own ON telegram_link_codes;
DROP POLICY IF EXISTS telegram_link_codes_update_own ON telegram_link_codes;
DROP POLICY IF EXISTS telegram_link_codes_delete_own ON telegram_link_codes;

CREATE POLICY documents_select_own
ON documents FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY documents_insert_own
ON documents FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY documents_update_own
ON documents FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY documents_delete_own
ON documents FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY vault_items_select_own
ON vault_items FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY vault_items_insert_own
ON vault_items FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY vault_items_update_own
ON vault_items FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY vault_items_delete_own
ON vault_items FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY telegram_link_codes_select_own
ON telegram_link_codes FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY telegram_link_codes_insert_own
ON telegram_link_codes FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY telegram_link_codes_update_own
ON telegram_link_codes FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY telegram_link_codes_delete_own
ON telegram_link_codes FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('keeba-files', 'keeba-files', TRUE, 15728640)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS storage_select_own ON storage.objects;
DROP POLICY IF EXISTS storage_insert_own ON storage.objects;
DROP POLICY IF EXISTS storage_update_own ON storage.objects;
DROP POLICY IF EXISTS storage_delete_own ON storage.objects;

CREATE POLICY storage_select_own
ON storage.objects FOR SELECT
TO authenticated
USING (
	bucket_id = 'keeba-files'
	AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_insert_own
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
	bucket_id = 'keeba-files'
	AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_update_own
ON storage.objects FOR UPDATE
TO authenticated
USING (
	bucket_id = 'keeba-files'
	AND (storage.foldername(name))[1] = auth.uid()::TEXT
)
WITH CHECK (
	bucket_id = 'keeba-files'
	AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_delete_own
ON storage.objects FOR DELETE
TO authenticated
USING (
	bucket_id = 'keeba-files'
	AND (storage.foldername(name))[1] = auth.uid()::TEXT
);
CREATE TABLE IF NOT EXISTS journal_threads (
id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
title TEXT NOT NULL DEFAULT 'New Journal',
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS journal_entries (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
journal_id UUID NOT NULL REFERENCES journal_threads(id) ON DELETE CASCADE,
user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
content TEXT NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE journal_threads ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY journal_threads_select_own ON journal_threads FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY journal_threads_insert_own ON journal_threads FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY journal_threads_update_own ON journal_threads FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY journal_threads_delete_own ON journal_threads FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE POLICY journal_entries_select_own ON journal_entries FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY journal_entries_insert_own ON journal_entries FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY journal_entries_update_own ON journal_entries FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY journal_entries_delete_own ON journal_entries FOR DELETE TO authenticated USING (auth.uid() = user_id);
CREATE TABLE IF NOT EXISTS reminders (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
task TEXT NOT NULL,
due_at TIMESTAMPTZ NOT NULL,
status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
telegram_chat_id BIGINT,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;
CREATE POLICY reminders_select_own ON reminders FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY reminders_insert_own ON reminders FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY reminders_update_own ON reminders FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY reminders_delete_own ON reminders FOR DELETE TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_reminders_pending_due_at ON reminders (due_at) WHERE status = 'pending';
