CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  date_of_birth DATE,
  phone TEXT,
  address TEXT,
  occupation TEXT,
  about_me TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_user_created_at
  ON chat_messages (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('aadhaar', 'passport', 'license', 'certificate', 'photo', 'other')),
  file_url TEXT NOT NULL,
  storage_bucket TEXT NOT NULL DEFAULT 'keeba-files',
  storage_path TEXT NOT NULL,
  extracted_text TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_documents_user_created_at
  ON documents (user_id, created_at DESC);

CREATE OR REPLACE FUNCTION update_profiles_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON profiles;

CREATE TRIGGER trg_profiles_updated_at
BEFORE UPDATE ON profiles
FOR EACH ROW
EXECUTE FUNCTION update_profiles_timestamp();

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON profiles;
DROP POLICY IF EXISTS profiles_insert_own ON profiles;
DROP POLICY IF EXISTS profiles_update_own ON profiles;
DROP POLICY IF EXISTS profiles_delete_own ON profiles;

CREATE POLICY profiles_select_own
ON profiles FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY profiles_insert_own
ON profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY profiles_update_own
ON profiles FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY profiles_delete_own
ON profiles FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS chat_messages_select_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_insert_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_update_own ON chat_messages;
DROP POLICY IF EXISTS chat_messages_delete_own ON chat_messages;

CREATE POLICY chat_messages_select_own
ON chat_messages FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY chat_messages_insert_own
ON chat_messages FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_messages_update_own
ON chat_messages FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY chat_messages_delete_own
ON chat_messages FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS documents_select_own ON documents;
DROP POLICY IF EXISTS documents_insert_own ON documents;
DROP POLICY IF EXISTS documents_update_own ON documents;
DROP POLICY IF EXISTS documents_delete_own ON documents;

CREATE POLICY documents_select_own
ON documents FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY documents_insert_own
ON documents FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY documents_update_own
ON documents FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY documents_delete_own
ON documents FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('keeba-files', 'keeba-files', TRUE, 15728640)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS storage_select_own ON storage.objects;
DROP POLICY IF EXISTS storage_insert_own ON storage.objects;
DROP POLICY IF EXISTS storage_update_own ON storage.objects;
DROP POLICY IF EXISTS storage_delete_own ON storage.objects;

CREATE POLICY storage_select_own
ON storage.objects FOR SELECT
TO authenticated
USING (
  bucket_id = 'keeba-files'
  AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_insert_own
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'keeba-files'
  AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_update_own
ON storage.objects FOR UPDATE
TO authenticated
USING (
  bucket_id = 'keeba-files'
  AND (storage.foldername(name))[1] = auth.uid()::TEXT
)
WITH CHECK (
  bucket_id = 'keeba-files'
  AND (storage.foldername(name))[1] = auth.uid()::TEXT
);

CREATE POLICY storage_delete_own
ON storage.objects FOR DELETE
TO authenticated
USING (
  bucket_id = 'keeba-files'
  AND (storage.foldername(name))[1] = auth.uid()::TEXT
);
